-- SQL Retail Sales Analysis - Project_01

CREATE DATABASE Project_01;

-- Create Table

CREATE TABLE retail_sales(

transactions_id	INT PRIMARY KEY NOT NULL,
sale_date DATE,
sale_time TIME,
customer_id	INT,
gender VARCHAR(15),
age	INT,
category VARCHAR(15),
quantity INT,
price_per_unit FLOAT,
cogs FLOAT,
total_sale FLOAT

);

SELECT * FROM retail_sales;

-- Data Cleaning

-- How many sales we have ?
SELECT COUNT(*)
FROM retail_sales;

SELECT *
FROM retail_sales
LIMIT 10;

SELECT * FROM retail_sales
WHERE transactions_id IS NULL;

SELECT * FROM retail_sales
WHERE sale_date IS NULL;

SELECT * FROM retail_sales
WHERE
	transactions_id IS NULL
	OR
	sale_date IS NULL
	OR
	sale_time IS NULL
	OR
	customer_id IS NULL
	OR
	gender IS NULL
	OR
	age IS NULL
	OR
	category IS NULL
	OR
	quantity IS NULL
	OR
	price_per_unit IS NULL
	OR
	cogs IS NULL
	OR
	total_sale IS NULL
	;

DELETE FROM retail_sales
WHERE
	transactions_id IS NULL
	OR
	sale_date IS NULL
	OR
	sale_time IS NULL
	OR
	customer_id IS NULL
	OR
	gender IS NULL
	OR
	age IS NULL
	OR
	category IS NULL
	OR
	quantity IS NULL
	OR
	price_per_unit IS NULL
	OR
	cogs IS NULL
	OR
	total_sale IS NULL
	;

SELECT  -- check dublicate values
    transactions_id,
    COUNT(*)
FROM retail_sales
GROUP BY transactions_id
HAVING COUNT(*) > 1;

SELECT *
FROM retail_sales
WHERE
    quantiy <= 0
    OR price_per_unit <= 0
    OR cogs <= 0
    OR total_sale <= 0;



-- Exploratory Data Analysis (EDA)

-- Que: 01:- Find the total number of sales transactions in the retail_sales table.
SELECT count(transactions_id) as total_transactions FROM retail_sales;

-- Que: 02:- Find the total number of unique customers who made purchases.
SELECT count(DISTINCT(customer_id)) AS total_unque_customers FROM retail_sales;

-- Que: 03:- Find all unique product categories available in the dataset.
SELECT DISTINCT category AS unique_products FROM retail_sales
ORDER by category;

-- Que: 04:- Find the total sales revenue generated by the store.
SELECT SUM(total_sale) AS total_sale from retail_sales;

-- Que: 05:- Show the first 5 Electronics transactions.
SELECT *
FROM retail_sales
WHERE category = 'Electronics'
LIMIT 15;

-- Q.6 Write a SQL query to retrieve all columns for sales made on '2022-11-05
SELECT * FROM retail_sales WHERE sale_date = '2022-11-05';

-- Q.7 Write a SQL query to retrieve all transactions where the category is 'Clothing' and the quantity sold is more than 10 in the month of Nov-2022
SELECT * FROM retail_sales
WHERE category = 'Clothing' AND quantity > '10' AND
sale_date BETWEEN '2022-11-01' AND '2022-11-30';

-- Q.8 Write a SQL query to calculate the total sales (total_sale) for each category.
SELECT category, SUM(total_sale) AS total_sales FROM retail_sales GROUP BY category;

-- Q.9 Write a SQL query to find the average age of customers who purchased items from the 'Beauty' category.
SELECT AVG(age) AS avg_age FROM retail_sales WHERE category = 'Beauty';

-- Q.10 Write a SQL query to find all transactions where the total_sale is greater than 1000.
SELECT * FROM retail_sales WHERE total_sale > 1000;

-- Q.11 Write a SQL query to find the total number of transactions (transaction_id) made by each gender in each category.
SELECT gender, category, count(transactions_id) AS total_transactions FROM retail_sales GROUP BY gender, category;

-- Q.12 Write a SQL query to calculate the average sale for each month. Find out best selling month in each year
SELECT
    EXTRACT(YEAR FROM sale_date) AS year,
    EXTRACT(MONTH FROM sale_date) AS month,
    AVG(total_sale) AS avg_sales
FROM retail_sales
GROUP BY 1, 2
ORDER BY 1, 3 DESC;


-- Q.13 Write a SQL query to find the top 5 customers based on the highest total sales
SELECT
    customer_id,
    SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY customer_id
ORDER BY total_sales DESC
LIMIT 5;


-- Q.14 Write a SQL query to find the number of unique customers who purchased items from each category.
SELECT
    category,
    COUNT(DISTINCT customer_id) AS unique_customers
FROM retail_sales
GROUP BY category
ORDER BY unique_customers DESC;


-- Q.15 Write a SQL query to create each shift and number of orders (Example Morning <=12, Afternoon Between 12 & 17, Evening >17)
SELECT
    CASE
        WHEN EXTRACT(HOUR FROM sale_time) < 12 THEN 'Morning'
        WHEN EXTRACT(HOUR FROM sale_time) BETWEEN 12 AND 17 THEN 'Afternoon'
        ELSE 'Evening'
    END AS shift,
    COUNT(*) AS number_of_orders
FROM retail_sales
GROUP BY shift
ORDER BY number_of_orders DESC;
 
-- End of project